name: flutter_grab
description: Grab login page clone using Flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  gap: ^3.0.1
  sign_in_button: ^3.2.0

dependency_overrides:
  font_awesome_flutter: 10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/google.png
    - assets/image/grab.png
    - assets/image/facebook.png